// Code generated by MockGen. DO NOT EDIT.
// Source: remindlist_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	command "github.com/enrico5b1b4/telegram-bot/pkg/command"
	gomock "github.com/golang/mock/gomock"
)

// MockRemindListServicer is a mock of RemindListServicer interface
type MockRemindListServicer struct {
	ctrl     *gomock.Controller
	recorder *MockRemindListServicerMockRecorder
}

// MockRemindListServicerMockRecorder is the mock recorder for MockRemindListServicer
type MockRemindListServicerMockRecorder struct {
	mock *MockRemindListServicer
}

// NewMockRemindListServicer creates a new mock instance
func NewMockRemindListServicer(ctrl *gomock.Controller) *MockRemindListServicer {
	mock := &MockRemindListServicer{ctrl: ctrl}
	mock.recorder = &MockRemindListServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRemindListServicer) EXPECT() *MockRemindListServicerMockRecorder {
	return m.recorder
}

// GetRemindersByChatID mocks base method
func (m *MockRemindListServicer) GetRemindersByChatID(chatID int) ([]command.ByJobStatusList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemindersByChatID", chatID)
	ret0, _ := ret[0].([]command.ByJobStatusList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemindersByChatID indicates an expected call of GetRemindersByChatID
func (mr *MockRemindListServicerMockRecorder) GetRemindersByChatID(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemindersByChatID", reflect.TypeOf((*MockRemindListServicer)(nil).GetRemindersByChatID), chatID)
}

// RemoveCompletedReminders mocks base method
func (m *MockRemindListServicer) RemoveCompletedReminders(chatID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCompletedReminders", chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCompletedReminders indicates an expected call of RemoveCompletedReminders
func (mr *MockRemindListServicerMockRecorder) RemoveCompletedReminders(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCompletedReminders", reflect.TypeOf((*MockRemindListServicer)(nil).RemoveCompletedReminders), chatID)
}
