// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cron "github.com/enrico5b1b4/telegram-bot/pkg/cron"
	gomock "github.com/golang/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockScheduler) Add(spec string, cmd func()) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", spec, cmd)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add
func (mr *MockSchedulerMockRecorder) Add(spec, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockScheduler)(nil).Add), spec, cmd)
}

// Remove mocks base method
func (m *MockScheduler) Remove(ID int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", ID)
}

// Remove indicates an expected call of Remove
func (mr *MockSchedulerMockRecorder) Remove(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockScheduler)(nil).Remove), ID)
}

// GetEntryByID mocks base method
func (m *MockScheduler) GetEntryByID(ID int) cron.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryByID", ID)
	ret0, _ := ret[0].(cron.Entry)
	return ret0
}

// GetEntryByID indicates an expected call of GetEntryByID
func (mr *MockSchedulerMockRecorder) GetEntryByID(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryByID", reflect.TypeOf((*MockScheduler)(nil).GetEntryByID), ID)
}

// Start mocks base method
func (m *MockScheduler) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start
func (mr *MockSchedulerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockScheduler)(nil).Start))
}

// Stop mocks base method
func (m *MockScheduler) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop
func (mr *MockSchedulerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockScheduler)(nil).Stop))
}
